# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/simple_hdmi/simple_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi || ORIG_REF_NAME==simple_hdmi} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_processing_system7_0_0/simple_hdmi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_processing_system7_0_0 || ORIG_REF_NAME==simple_hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_hdmi_top_0_0/simple_hdmi_hdmi_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_hdmi_top_0_0 || ORIG_REF_NAME==simple_hdmi_hdmi_top_0_0} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_axi_vdma_0_0/simple_hdmi_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==simple_hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_axi_smc_0/simple_hdmi_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_axi_smc_0 || ORIG_REF_NAME==simple_hdmi_axi_smc_0} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_rst_ps7_0_100M_0/simple_hdmi_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_rst_ps7_0_100M_0 || ORIG_REF_NAME==simple_hdmi_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/simple_hdmi/ip/simple_hdmi_axi_intc_0_0/simple_hdmi_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple_hdmi_axi_intc_0_0 || ORIG_REF_NAME==simple_hdmi_axi_intc_0_0} -quiet] -quiet

# XDC: /home/njordan/Development/fpga/pynq_z2_hdmi_demo/pynq_z2_hdmi_demo.gen/sources_1/bd/simple_hdmi/simple_hdmi_ooc.xdc
