# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/njordan/Development/fpga/simple_hdmi/simple_hdmi.srcs/sources_1/bd/simple_hdmi/ip/simple_hdmi_processing_system7_0_0/simple_hdmi_processing_system7_0_0.xci
# IP: The module: 'simple_hdmi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/njordan/Development/fpga/simple_hdmi/simple_hdmi.gen/sources_1/bd/simple_hdmi/ip/simple_hdmi_processing_system7_0_0/simple_hdmi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_hdmi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/njordan/Development/fpga/simple_hdmi/simple_hdmi.srcs/sources_1/bd/simple_hdmi/ip/simple_hdmi_processing_system7_0_0/simple_hdmi_processing_system7_0_0.xci
# IP: The module: 'simple_hdmi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/njordan/Development/fpga/simple_hdmi/simple_hdmi.gen/sources_1/bd/simple_hdmi/ip/simple_hdmi_processing_system7_0_0/simple_hdmi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_hdmi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
